# 공통설정
spring:
  profiles:
    active:
      - dev
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 100MB

  application:
    name: withbooks

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: name

fileupload:
  contextPath: /home/withbooks/webapps/image/
  